/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingInstitutionsRouteImport } from './routes/training-institutions'
import { Route as StrategicPlanRouteImport } from './routes/strategic-plan'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisteredSubscribedMembersRouteImport } from './routes/registered-subscribed-members'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CpdRouteImport } from './routes/cpd'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MembershipFormRouteRouteImport } from './routes/membership-form/route'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembershipFormIndexRouteImport } from './routes/membership-form/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as NewsPpauUhpabTranscriptsRouteImport } from './routes/news.ppau-uhpab-transcripts'
import { Route as NewsPpauNdhpactAlarmRouteImport } from './routes/news.ppau-ndhpact-alarm'
import { Route as NewsPharmacyProfessionalsMarketingRouteImport } from './routes/news.pharmacy-professionals-marketing'
import { Route as NewsNdaAhpcPpauMeetingRouteImport } from './routes/news.nda-ahpc-ppau-meeting'
import { Route as NewsFamilyPlanningServicesRouteImport } from './routes/news.family-planning-services'
import { Route as MembershipFormSuccessRouteImport } from './routes/membership-form/success'
import { Route as MembershipFormStudentRouteImport } from './routes/membership-form/student'
import { Route as MembershipFormProfessionalRouteImport } from './routes/membership-form/professional'
import { Route as MembershipFormPaymentRouteImport } from './routes/membership-form/payment'
import { Route as MemberSetPasswordRouteImport } from './routes/member/set-password'
import { Route as MemberRenewRouteImport } from './routes/member/renew'
import { Route as MemberPaymentsRouteImport } from './routes/member/payments'
import { Route as MemberLoginRouteImport } from './routes/member/login'
import { Route as MemberForgotPasswordRouteImport } from './routes/member/forgot-password'
import { Route as MemberApplicationRouteImport } from './routes/member/application'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMigrationRouteImport } from './routes/admin/migration'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminEmailRouteRouteImport } from './routes/admin/email/route'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as MembershipFormPaymentCallbackRouteImport } from './routes/membership-form/payment.callback'
import { Route as MemberRenewCallbackRouteImport } from './routes/member/renew.callback'
import { Route as AdminMembersRejectedRouteImport } from './routes/admin/members.rejected'
import { Route as AdminMembersAcceptedRouteImport } from './routes/admin/members.accepted'
import { Route as AdminFormsStudentRouteImport } from './routes/admin/forms.student'
import { Route as AdminFormsProfessionalRouteImport } from './routes/admin/forms.professional'
import { Route as AdminEmailSettingsRouteImport } from './routes/admin/email/settings'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin/applications.$id'
import { Route as AdminEmailTemplatesRouteRouteImport } from './routes/admin/email/templates/route'
import { Route as AdminEmailTemplatesIndexRouteImport } from './routes/admin/email/templates/index'
import { Route as AdminEmailTemplatesSlugRouteImport } from './routes/admin/email/templates/$slug'

const TrainingInstitutionsRoute = TrainingInstitutionsRouteImport.update({
  id: '/training-institutions',
  path: '/training-institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicPlanRoute = StrategicPlanRouteImport.update({
  id: '/strategic-plan',
  path: '/strategic-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisteredSubscribedMembersRoute =
  RegisteredSubscribedMembersRouteImport.update({
    id: '/registered-subscribed-members',
    path: '/registered-subscribed-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRoute = CpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipFormRouteRoute = MembershipFormRouteRouteImport.update({
  id: '/membership-form',
  path: '/membership-form',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipFormIndexRoute = MembershipFormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembershipFormRouteRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NewsPpauUhpabTranscriptsRoute =
  NewsPpauUhpabTranscriptsRouteImport.update({
    id: '/ppau-uhpab-transcripts',
    path: '/ppau-uhpab-transcripts',
    getParentRoute: () => NewsRoute,
  } as any)
const NewsPpauNdhpactAlarmRoute = NewsPpauNdhpactAlarmRouteImport.update({
  id: '/ppau-ndhpact-alarm',
  path: '/ppau-ndhpact-alarm',
  getParentRoute: () => NewsRoute,
} as any)
const NewsPharmacyProfessionalsMarketingRoute =
  NewsPharmacyProfessionalsMarketingRouteImport.update({
    id: '/pharmacy-professionals-marketing',
    path: '/pharmacy-professionals-marketing',
    getParentRoute: () => NewsRoute,
  } as any)
const NewsNdaAhpcPpauMeetingRoute = NewsNdaAhpcPpauMeetingRouteImport.update({
  id: '/nda-ahpc-ppau-meeting',
  path: '/nda-ahpc-ppau-meeting',
  getParentRoute: () => NewsRoute,
} as any)
const NewsFamilyPlanningServicesRoute =
  NewsFamilyPlanningServicesRouteImport.update({
    id: '/family-planning-services',
    path: '/family-planning-services',
    getParentRoute: () => NewsRoute,
  } as any)
const MembershipFormSuccessRoute = MembershipFormSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MembershipFormRouteRoute,
} as any)
const MembershipFormStudentRoute = MembershipFormStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => MembershipFormRouteRoute,
} as any)
const MembershipFormProfessionalRoute =
  MembershipFormProfessionalRouteImport.update({
    id: '/professional',
    path: '/professional',
    getParentRoute: () => MembershipFormRouteRoute,
  } as any)
const MembershipFormPaymentRoute = MembershipFormPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => MembershipFormRouteRoute,
} as any)
const MemberSetPasswordRoute = MemberSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberRenewRoute = MemberRenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberPaymentsRoute = MemberPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberForgotPasswordRoute = MemberForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberApplicationRoute = MemberApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailRouteRoute = AdminEmailRouteRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MembershipFormPaymentCallbackRoute =
  MembershipFormPaymentCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => MembershipFormPaymentRoute,
  } as any)
const MemberRenewCallbackRoute = MemberRenewCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => MemberRenewRoute,
} as any)
const AdminMembersRejectedRoute = AdminMembersRejectedRouteImport.update({
  id: '/members/rejected',
  path: '/members/rejected',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersAcceptedRoute = AdminMembersAcceptedRouteImport.update({
  id: '/members/accepted',
  path: '/members/accepted',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsStudentRoute = AdminFormsStudentRouteImport.update({
  id: '/forms/student',
  path: '/forms/student',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsProfessionalRoute = AdminFormsProfessionalRouteImport.update({
  id: '/forms/professional',
  path: '/forms/professional',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailSettingsRoute = AdminEmailSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminEmailRouteRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailTemplatesRouteRoute =
  AdminEmailTemplatesRouteRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AdminEmailRouteRoute,
  } as any)
const AdminEmailTemplatesIndexRoute =
  AdminEmailTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEmailTemplatesRouteRoute,
  } as any)
const AdminEmailTemplatesSlugRoute = AdminEmailTemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminEmailTemplatesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/membership-form': typeof MembershipFormRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/committee': typeof CommitteeRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cpd': typeof CpdRoute
  '/events': typeof EventsRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/registered-subscribed-members': typeof RegisteredSubscribedMembersRoute
  '/resources': typeof ResourcesRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/training-institutions': typeof TrainingInstitutionsRoute
  '/admin/email': typeof AdminEmailRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/application': typeof MemberApplicationRoute
  '/member/forgot-password': typeof MemberForgotPasswordRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/renew': typeof MemberRenewRouteWithChildren
  '/member/set-password': typeof MemberSetPasswordRoute
  '/membership-form/payment': typeof MembershipFormPaymentRouteWithChildren
  '/membership-form/professional': typeof MembershipFormProfessionalRoute
  '/membership-form/student': typeof MembershipFormStudentRoute
  '/membership-form/success': typeof MembershipFormSuccessRoute
  '/news/family-planning-services': typeof NewsFamilyPlanningServicesRoute
  '/news/nda-ahpc-ppau-meeting': typeof NewsNdaAhpcPpauMeetingRoute
  '/news/pharmacy-professionals-marketing': typeof NewsPharmacyProfessionalsMarketingRoute
  '/news/ppau-ndhpact-alarm': typeof NewsPpauNdhpactAlarmRoute
  '/news/ppau-uhpab-transcripts': typeof NewsPpauUhpabTranscriptsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/membership-form/': typeof MembershipFormIndexRoute
  '/admin/email/templates': typeof AdminEmailTemplatesRouteRouteWithChildren
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/email/settings': typeof AdminEmailSettingsRoute
  '/admin/forms/professional': typeof AdminFormsProfessionalRoute
  '/admin/forms/student': typeof AdminFormsStudentRoute
  '/admin/members/accepted': typeof AdminMembersAcceptedRoute
  '/admin/members/rejected': typeof AdminMembersRejectedRoute
  '/member/renew/callback': typeof MemberRenewCallbackRoute
  '/membership-form/payment/callback': typeof MembershipFormPaymentCallbackRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/email/templates/$slug': typeof AdminEmailTemplatesSlugRoute
  '/admin/email/templates/': typeof AdminEmailTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/committee': typeof CommitteeRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cpd': typeof CpdRoute
  '/events': typeof EventsRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/registered-subscribed-members': typeof RegisteredSubscribedMembersRoute
  '/resources': typeof ResourcesRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/training-institutions': typeof TrainingInstitutionsRoute
  '/admin/email': typeof AdminEmailRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/application': typeof MemberApplicationRoute
  '/member/forgot-password': typeof MemberForgotPasswordRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/renew': typeof MemberRenewRouteWithChildren
  '/member/set-password': typeof MemberSetPasswordRoute
  '/membership-form/payment': typeof MembershipFormPaymentRouteWithChildren
  '/membership-form/professional': typeof MembershipFormProfessionalRoute
  '/membership-form/student': typeof MembershipFormStudentRoute
  '/membership-form/success': typeof MembershipFormSuccessRoute
  '/news/family-planning-services': typeof NewsFamilyPlanningServicesRoute
  '/news/nda-ahpc-ppau-meeting': typeof NewsNdaAhpcPpauMeetingRoute
  '/news/pharmacy-professionals-marketing': typeof NewsPharmacyProfessionalsMarketingRoute
  '/news/ppau-ndhpact-alarm': typeof NewsPpauNdhpactAlarmRoute
  '/news/ppau-uhpab-transcripts': typeof NewsPpauUhpabTranscriptsRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/membership-form': typeof MembershipFormIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/email/settings': typeof AdminEmailSettingsRoute
  '/admin/forms/professional': typeof AdminFormsProfessionalRoute
  '/admin/forms/student': typeof AdminFormsStudentRoute
  '/admin/members/accepted': typeof AdminMembersAcceptedRoute
  '/admin/members/rejected': typeof AdminMembersRejectedRoute
  '/member/renew/callback': typeof MemberRenewCallbackRoute
  '/membership-form/payment/callback': typeof MembershipFormPaymentCallbackRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/email/templates/$slug': typeof AdminEmailTemplatesSlugRoute
  '/admin/email/templates': typeof AdminEmailTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/membership-form': typeof MembershipFormRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/committee': typeof CommitteeRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cpd': typeof CpdRoute
  '/events': typeof EventsRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/registered-subscribed-members': typeof RegisteredSubscribedMembersRoute
  '/resources': typeof ResourcesRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/training-institutions': typeof TrainingInstitutionsRoute
  '/admin/email': typeof AdminEmailRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/application': typeof MemberApplicationRoute
  '/member/forgot-password': typeof MemberForgotPasswordRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/renew': typeof MemberRenewRouteWithChildren
  '/member/set-password': typeof MemberSetPasswordRoute
  '/membership-form/payment': typeof MembershipFormPaymentRouteWithChildren
  '/membership-form/professional': typeof MembershipFormProfessionalRoute
  '/membership-form/student': typeof MembershipFormStudentRoute
  '/membership-form/success': typeof MembershipFormSuccessRoute
  '/news/family-planning-services': typeof NewsFamilyPlanningServicesRoute
  '/news/nda-ahpc-ppau-meeting': typeof NewsNdaAhpcPpauMeetingRoute
  '/news/pharmacy-professionals-marketing': typeof NewsPharmacyProfessionalsMarketingRoute
  '/news/ppau-ndhpact-alarm': typeof NewsPpauNdhpactAlarmRoute
  '/news/ppau-uhpab-transcripts': typeof NewsPpauUhpabTranscriptsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/membership-form/': typeof MembershipFormIndexRoute
  '/admin/email/templates': typeof AdminEmailTemplatesRouteRouteWithChildren
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/email/settings': typeof AdminEmailSettingsRoute
  '/admin/forms/professional': typeof AdminFormsProfessionalRoute
  '/admin/forms/student': typeof AdminFormsStudentRoute
  '/admin/members/accepted': typeof AdminMembersAcceptedRoute
  '/admin/members/rejected': typeof AdminMembersRejectedRoute
  '/member/renew/callback': typeof MemberRenewCallbackRoute
  '/membership-form/payment/callback': typeof MembershipFormPaymentCallbackRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/email/templates/$slug': typeof AdminEmailTemplatesSlugRoute
  '/admin/email/templates/': typeof AdminEmailTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/membership-form'
    | '/about'
    | '/committee'
    | '/community'
    | '/contact'
    | '/cpd'
    | '/events'
    | '/membership'
    | '/news'
    | '/registered-subscribed-members'
    | '/resources'
    | '/strategic-plan'
    | '/training-institutions'
    | '/admin/email'
    | '/admin/admins'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/migration'
    | '/admin/payments'
    | '/member/application'
    | '/member/forgot-password'
    | '/member/login'
    | '/member/payments'
    | '/member/renew'
    | '/member/set-password'
    | '/membership-form/payment'
    | '/membership-form/professional'
    | '/membership-form/student'
    | '/membership-form/success'
    | '/news/family-planning-services'
    | '/news/nda-ahpc-ppau-meeting'
    | '/news/pharmacy-professionals-marketing'
    | '/news/ppau-ndhpact-alarm'
    | '/news/ppau-uhpab-transcripts'
    | '/admin/'
    | '/member/'
    | '/membership-form/'
    | '/admin/email/templates'
    | '/admin/applications/$id'
    | '/admin/email/settings'
    | '/admin/forms/professional'
    | '/admin/forms/student'
    | '/admin/members/accepted'
    | '/admin/members/rejected'
    | '/member/renew/callback'
    | '/membership-form/payment/callback'
    | '/admin/applications/'
    | '/admin/email/templates/$slug'
    | '/admin/email/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/committee'
    | '/community'
    | '/contact'
    | '/cpd'
    | '/events'
    | '/membership'
    | '/news'
    | '/registered-subscribed-members'
    | '/resources'
    | '/strategic-plan'
    | '/training-institutions'
    | '/admin/email'
    | '/admin/admins'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/migration'
    | '/admin/payments'
    | '/member/application'
    | '/member/forgot-password'
    | '/member/login'
    | '/member/payments'
    | '/member/renew'
    | '/member/set-password'
    | '/membership-form/payment'
    | '/membership-form/professional'
    | '/membership-form/student'
    | '/membership-form/success'
    | '/news/family-planning-services'
    | '/news/nda-ahpc-ppau-meeting'
    | '/news/pharmacy-professionals-marketing'
    | '/news/ppau-ndhpact-alarm'
    | '/news/ppau-uhpab-transcripts'
    | '/admin'
    | '/member'
    | '/membership-form'
    | '/admin/applications/$id'
    | '/admin/email/settings'
    | '/admin/forms/professional'
    | '/admin/forms/student'
    | '/admin/members/accepted'
    | '/admin/members/rejected'
    | '/member/renew/callback'
    | '/membership-form/payment/callback'
    | '/admin/applications'
    | '/admin/email/templates/$slug'
    | '/admin/email/templates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/membership-form'
    | '/about'
    | '/committee'
    | '/community'
    | '/contact'
    | '/cpd'
    | '/events'
    | '/membership'
    | '/news'
    | '/registered-subscribed-members'
    | '/resources'
    | '/strategic-plan'
    | '/training-institutions'
    | '/admin/email'
    | '/admin/admins'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/migration'
    | '/admin/payments'
    | '/member/application'
    | '/member/forgot-password'
    | '/member/login'
    | '/member/payments'
    | '/member/renew'
    | '/member/set-password'
    | '/membership-form/payment'
    | '/membership-form/professional'
    | '/membership-form/student'
    | '/membership-form/success'
    | '/news/family-planning-services'
    | '/news/nda-ahpc-ppau-meeting'
    | '/news/pharmacy-professionals-marketing'
    | '/news/ppau-ndhpact-alarm'
    | '/news/ppau-uhpab-transcripts'
    | '/admin/'
    | '/member/'
    | '/membership-form/'
    | '/admin/email/templates'
    | '/admin/applications/$id'
    | '/admin/email/settings'
    | '/admin/forms/professional'
    | '/admin/forms/student'
    | '/admin/members/accepted'
    | '/admin/members/rejected'
    | '/member/renew/callback'
    | '/membership-form/payment/callback'
    | '/admin/applications/'
    | '/admin/email/templates/$slug'
    | '/admin/email/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  MembershipFormRouteRoute: typeof MembershipFormRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommitteeRoute: typeof CommitteeRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CpdRoute: typeof CpdRoute
  EventsRoute: typeof EventsRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRouteWithChildren
  RegisteredSubscribedMembersRoute: typeof RegisteredSubscribedMembersRoute
  ResourcesRoute: typeof ResourcesRoute
  StrategicPlanRoute: typeof StrategicPlanRoute
  TrainingInstitutionsRoute: typeof TrainingInstitutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-institutions': {
      id: '/training-institutions'
      path: '/training-institutions'
      fullPath: '/training-institutions'
      preLoaderRoute: typeof TrainingInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-plan': {
      id: '/strategic-plan'
      path: '/strategic-plan'
      fullPath: '/strategic-plan'
      preLoaderRoute: typeof StrategicPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registered-subscribed-members': {
      id: '/registered-subscribed-members'
      path: '/registered-subscribed-members'
      fullPath: '/registered-subscribed-members'
      preLoaderRoute: typeof RegisteredSubscribedMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd': {
      id: '/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof CpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-form': {
      id: '/membership-form'
      path: '/membership-form'
      fullPath: '/membership-form'
      preLoaderRoute: typeof MembershipFormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-form/': {
      id: '/membership-form/'
      path: '/'
      fullPath: '/membership-form/'
      preLoaderRoute: typeof MembershipFormIndexRouteImport
      parentRoute: typeof MembershipFormRouteRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/news/ppau-uhpab-transcripts': {
      id: '/news/ppau-uhpab-transcripts'
      path: '/ppau-uhpab-transcripts'
      fullPath: '/news/ppau-uhpab-transcripts'
      preLoaderRoute: typeof NewsPpauUhpabTranscriptsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/ppau-ndhpact-alarm': {
      id: '/news/ppau-ndhpact-alarm'
      path: '/ppau-ndhpact-alarm'
      fullPath: '/news/ppau-ndhpact-alarm'
      preLoaderRoute: typeof NewsPpauNdhpactAlarmRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/pharmacy-professionals-marketing': {
      id: '/news/pharmacy-professionals-marketing'
      path: '/pharmacy-professionals-marketing'
      fullPath: '/news/pharmacy-professionals-marketing'
      preLoaderRoute: typeof NewsPharmacyProfessionalsMarketingRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/nda-ahpc-ppau-meeting': {
      id: '/news/nda-ahpc-ppau-meeting'
      path: '/nda-ahpc-ppau-meeting'
      fullPath: '/news/nda-ahpc-ppau-meeting'
      preLoaderRoute: typeof NewsNdaAhpcPpauMeetingRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/family-planning-services': {
      id: '/news/family-planning-services'
      path: '/family-planning-services'
      fullPath: '/news/family-planning-services'
      preLoaderRoute: typeof NewsFamilyPlanningServicesRouteImport
      parentRoute: typeof NewsRoute
    }
    '/membership-form/success': {
      id: '/membership-form/success'
      path: '/success'
      fullPath: '/membership-form/success'
      preLoaderRoute: typeof MembershipFormSuccessRouteImport
      parentRoute: typeof MembershipFormRouteRoute
    }
    '/membership-form/student': {
      id: '/membership-form/student'
      path: '/student'
      fullPath: '/membership-form/student'
      preLoaderRoute: typeof MembershipFormStudentRouteImport
      parentRoute: typeof MembershipFormRouteRoute
    }
    '/membership-form/professional': {
      id: '/membership-form/professional'
      path: '/professional'
      fullPath: '/membership-form/professional'
      preLoaderRoute: typeof MembershipFormProfessionalRouteImport
      parentRoute: typeof MembershipFormRouteRoute
    }
    '/membership-form/payment': {
      id: '/membership-form/payment'
      path: '/payment'
      fullPath: '/membership-form/payment'
      preLoaderRoute: typeof MembershipFormPaymentRouteImport
      parentRoute: typeof MembershipFormRouteRoute
    }
    '/member/set-password': {
      id: '/member/set-password'
      path: '/set-password'
      fullPath: '/member/set-password'
      preLoaderRoute: typeof MemberSetPasswordRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/renew': {
      id: '/member/renew'
      path: '/renew'
      fullPath: '/member/renew'
      preLoaderRoute: typeof MemberRenewRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/payments': {
      id: '/member/payments'
      path: '/payments'
      fullPath: '/member/payments'
      preLoaderRoute: typeof MemberPaymentsRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/login': {
      id: '/member/login'
      path: '/login'
      fullPath: '/member/login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/forgot-password': {
      id: '/member/forgot-password'
      path: '/forgot-password'
      fullPath: '/member/forgot-password'
      preLoaderRoute: typeof MemberForgotPasswordRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/application': {
      id: '/member/application'
      path: '/application'
      fullPath: '/member/application'
      preLoaderRoute: typeof MemberApplicationRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/membership-form/payment/callback': {
      id: '/membership-form/payment/callback'
      path: '/callback'
      fullPath: '/membership-form/payment/callback'
      preLoaderRoute: typeof MembershipFormPaymentCallbackRouteImport
      parentRoute: typeof MembershipFormPaymentRoute
    }
    '/member/renew/callback': {
      id: '/member/renew/callback'
      path: '/callback'
      fullPath: '/member/renew/callback'
      preLoaderRoute: typeof MemberRenewCallbackRouteImport
      parentRoute: typeof MemberRenewRoute
    }
    '/admin/members/rejected': {
      id: '/admin/members/rejected'
      path: '/members/rejected'
      fullPath: '/admin/members/rejected'
      preLoaderRoute: typeof AdminMembersRejectedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members/accepted': {
      id: '/admin/members/accepted'
      path: '/members/accepted'
      fullPath: '/admin/members/accepted'
      preLoaderRoute: typeof AdminMembersAcceptedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/student': {
      id: '/admin/forms/student'
      path: '/forms/student'
      fullPath: '/admin/forms/student'
      preLoaderRoute: typeof AdminFormsStudentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/professional': {
      id: '/admin/forms/professional'
      path: '/forms/professional'
      fullPath: '/admin/forms/professional'
      preLoaderRoute: typeof AdminFormsProfessionalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/settings': {
      id: '/admin/email/settings'
      path: '/settings'
      fullPath: '/admin/email/settings'
      preLoaderRoute: typeof AdminEmailSettingsRouteImport
      parentRoute: typeof AdminEmailRouteRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/templates': {
      id: '/admin/email/templates'
      path: '/templates'
      fullPath: '/admin/email/templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteRouteImport
      parentRoute: typeof AdminEmailRouteRoute
    }
    '/admin/email/templates/': {
      id: '/admin/email/templates/'
      path: '/'
      fullPath: '/admin/email/templates/'
      preLoaderRoute: typeof AdminEmailTemplatesIndexRouteImport
      parentRoute: typeof AdminEmailTemplatesRouteRoute
    }
    '/admin/email/templates/$slug': {
      id: '/admin/email/templates/$slug'
      path: '/$slug'
      fullPath: '/admin/email/templates/$slug'
      preLoaderRoute: typeof AdminEmailTemplatesSlugRouteImport
      parentRoute: typeof AdminEmailTemplatesRouteRoute
    }
  }
}

interface AdminEmailTemplatesRouteRouteChildren {
  AdminEmailTemplatesSlugRoute: typeof AdminEmailTemplatesSlugRoute
  AdminEmailTemplatesIndexRoute: typeof AdminEmailTemplatesIndexRoute
}

const AdminEmailTemplatesRouteRouteChildren: AdminEmailTemplatesRouteRouteChildren =
  {
    AdminEmailTemplatesSlugRoute: AdminEmailTemplatesSlugRoute,
    AdminEmailTemplatesIndexRoute: AdminEmailTemplatesIndexRoute,
  }

const AdminEmailTemplatesRouteRouteWithChildren =
  AdminEmailTemplatesRouteRoute._addFileChildren(
    AdminEmailTemplatesRouteRouteChildren,
  )

interface AdminEmailRouteRouteChildren {
  AdminEmailTemplatesRouteRoute: typeof AdminEmailTemplatesRouteRouteWithChildren
  AdminEmailSettingsRoute: typeof AdminEmailSettingsRoute
}

const AdminEmailRouteRouteChildren: AdminEmailRouteRouteChildren = {
  AdminEmailTemplatesRouteRoute: AdminEmailTemplatesRouteRouteWithChildren,
  AdminEmailSettingsRoute: AdminEmailSettingsRoute,
}

const AdminEmailRouteRouteWithChildren = AdminEmailRouteRoute._addFileChildren(
  AdminEmailRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminEmailRouteRoute: typeof AdminEmailRouteRouteWithChildren
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminFormsProfessionalRoute: typeof AdminFormsProfessionalRoute
  AdminFormsStudentRoute: typeof AdminFormsStudentRoute
  AdminMembersAcceptedRoute: typeof AdminMembersAcceptedRoute
  AdminMembersRejectedRoute: typeof AdminMembersRejectedRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEmailRouteRoute: AdminEmailRouteRouteWithChildren,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminFormsProfessionalRoute: AdminFormsProfessionalRoute,
  AdminFormsStudentRoute: AdminFormsStudentRoute,
  AdminMembersAcceptedRoute: AdminMembersAcceptedRoute,
  AdminMembersRejectedRoute: AdminMembersRejectedRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MemberRenewRouteChildren {
  MemberRenewCallbackRoute: typeof MemberRenewCallbackRoute
}

const MemberRenewRouteChildren: MemberRenewRouteChildren = {
  MemberRenewCallbackRoute: MemberRenewCallbackRoute,
}

const MemberRenewRouteWithChildren = MemberRenewRoute._addFileChildren(
  MemberRenewRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberApplicationRoute: typeof MemberApplicationRoute
  MemberForgotPasswordRoute: typeof MemberForgotPasswordRoute
  MemberLoginRoute: typeof MemberLoginRoute
  MemberPaymentsRoute: typeof MemberPaymentsRoute
  MemberRenewRoute: typeof MemberRenewRouteWithChildren
  MemberSetPasswordRoute: typeof MemberSetPasswordRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberApplicationRoute: MemberApplicationRoute,
  MemberForgotPasswordRoute: MemberForgotPasswordRoute,
  MemberLoginRoute: MemberLoginRoute,
  MemberPaymentsRoute: MemberPaymentsRoute,
  MemberRenewRoute: MemberRenewRouteWithChildren,
  MemberSetPasswordRoute: MemberSetPasswordRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

interface MembershipFormPaymentRouteChildren {
  MembershipFormPaymentCallbackRoute: typeof MembershipFormPaymentCallbackRoute
}

const MembershipFormPaymentRouteChildren: MembershipFormPaymentRouteChildren = {
  MembershipFormPaymentCallbackRoute: MembershipFormPaymentCallbackRoute,
}

const MembershipFormPaymentRouteWithChildren =
  MembershipFormPaymentRoute._addFileChildren(
    MembershipFormPaymentRouteChildren,
  )

interface MembershipFormRouteRouteChildren {
  MembershipFormPaymentRoute: typeof MembershipFormPaymentRouteWithChildren
  MembershipFormProfessionalRoute: typeof MembershipFormProfessionalRoute
  MembershipFormStudentRoute: typeof MembershipFormStudentRoute
  MembershipFormSuccessRoute: typeof MembershipFormSuccessRoute
  MembershipFormIndexRoute: typeof MembershipFormIndexRoute
}

const MembershipFormRouteRouteChildren: MembershipFormRouteRouteChildren = {
  MembershipFormPaymentRoute: MembershipFormPaymentRouteWithChildren,
  MembershipFormProfessionalRoute: MembershipFormProfessionalRoute,
  MembershipFormStudentRoute: MembershipFormStudentRoute,
  MembershipFormSuccessRoute: MembershipFormSuccessRoute,
  MembershipFormIndexRoute: MembershipFormIndexRoute,
}

const MembershipFormRouteRouteWithChildren =
  MembershipFormRouteRoute._addFileChildren(MembershipFormRouteRouteChildren)

interface NewsRouteChildren {
  NewsFamilyPlanningServicesRoute: typeof NewsFamilyPlanningServicesRoute
  NewsNdaAhpcPpauMeetingRoute: typeof NewsNdaAhpcPpauMeetingRoute
  NewsPharmacyProfessionalsMarketingRoute: typeof NewsPharmacyProfessionalsMarketingRoute
  NewsPpauNdhpactAlarmRoute: typeof NewsPpauNdhpactAlarmRoute
  NewsPpauUhpabTranscriptsRoute: typeof NewsPpauUhpabTranscriptsRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsFamilyPlanningServicesRoute: NewsFamilyPlanningServicesRoute,
  NewsNdaAhpcPpauMeetingRoute: NewsNdaAhpcPpauMeetingRoute,
  NewsPharmacyProfessionalsMarketingRoute:
    NewsPharmacyProfessionalsMarketingRoute,
  NewsPpauNdhpactAlarmRoute: NewsPpauNdhpactAlarmRoute,
  NewsPpauUhpabTranscriptsRoute: NewsPpauUhpabTranscriptsRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  MembershipFormRouteRoute: MembershipFormRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CommitteeRoute: CommitteeRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CpdRoute: CpdRoute,
  EventsRoute: EventsRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRouteWithChildren,
  RegisteredSubscribedMembersRoute: RegisteredSubscribedMembersRoute,
  ResourcesRoute: ResourcesRoute,
  StrategicPlanRoute: StrategicPlanRoute,
  TrainingInstitutionsRoute: TrainingInstitutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
